In [454]:
import pandas as pd
import sys
import numpy as np

In [455]:
df = pd.read_csv("df_test_with_meta_proba.csv")

In [456]:
sub = pd.read_csv("ourbestsub.csv")

In [457]:
sub_mean = df.groupby("seq_id").mean().fillna(0)
sub_mean = sub_mean.reset_index()

In [458]:
cls_cls = sub_mean.columns[30:]

In [459]:
det_cls = sub.columns[1:]

In [460]:
merged = sub_mean.merge(sub, how="outer", left_on="seq_id", right_on="Id")

In [461]:
new_rows = merged["seq_id"].isnull()
#merged.loc[new_rows] = 1.0

In [462]:
merged.loc[new_rows, cls_cls] = 1.0

In [463]:
sub.shape

(11057, 205)

In [464]:
merged.set_index('Id')

,seq_id,height,location,width,seq_frame_num,seq_num_frames,sub_location,num_observations_image,latitude,longitude,...,Predicted559,Predicted562,Predicted563,Predicted564,Predicted565,Predicted566,Predicted567,Predicted568,Predicted570,Predicted571
Id,,,,,,,,,,,,,,,,,,,,,
2966a68a-6fe2-11eb-844f-0242ac1c0002,2966a68a-6fe2-11eb-844f-0242ac1c0002,1024.0,20.0,1280.0,0.5,2.0,0.0,0.000000,17.508937,-89.412457,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
296781a4-6fe2-11eb-844f-0242ac1c0002,296781a4-6fe2-11eb-844f-0242ac1c0002,1080.0,161.0,1920.0,4.0,9.0,0.0,0.000000,17.368936,-89.327305,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2967a1fc-6fe2-11eb-844f-0242ac1c0002,2967a1fc-6fe2-11eb-844f-0242ac1c0002,1080.0,161.0,1920.0,0.0,1.0,0.0,0.000000,17.368936,-89.327305,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2967bdd6-6fe2-11eb-844f-0242ac1c0002,2967bdd6-6fe2-11eb-844f-0242ac1c0002,1024.0,161.0,1280.0,3.0,7.0,0.0,0.428571,17.368936,-89.327305,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29681182-6fe2-11eb-844f-0242ac1c0002,29681182-6fe2-11eb-844f-0242ac1c0002,1024.0,161.0,1280.0,2.0,5.0,0.0,0.000000,17.368936,-89.327305,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
a92609b4-0cd3-11eb-bed1-0242ac1c0002,a92609b4-0cd3-11eb-bed1-0242ac1c0002,1080.0,118.0,1920.0,4.5,10.0,0.0,1.000000,0.476961,36.862299,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
a9260a22-0cd3-11eb-bed1-0242ac1c0002,a9260a22-0cd3-11eb-bed1-0242ac1c0002,1080.0,118.0,1920.0,0.5,2.0,0.0,0.500000,0.476961,36.862299,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
a92614e0-0cd3-11eb-bed1-0242ac1c0002,a92614e0-0cd3-11eb-bed1-0242ac1c0002,1080.0,134.0,1920.0,4.5,10.0,0.0,1.500000,0.425966,36.861556,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
a9261544-0cd3-11eb-bed1-0242ac1c0002,a9261544-0cd3-11eb-bed1-0242ac1c0002,1080.0,134.0,1920.0,4.5,10.0,0.0,1.000000,0.425966,36.861556,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
a92616ca-0cd3-11eb-bed1-0242ac1c0002,a92616ca-0cd3-11eb-bed1-0242ac1c0002,1536.0,533.0,2048.0,4.5,10.0,0.0,0.300000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [465]:
print(sub[det_cls].sum().sum())

4685.0

In [505]:
mask = merged[cls_cls] > 0

In [506]:
mask.head()

,0,2,3,4,6,7,8,9,10,12,...,559,562,563,564,565,566,567,568,570,571
0,True,False,True,False,True,False,False,False,True,False,...,False,False,False,False,False,True,False,True,False,False
1,True,True,True,False,True,True,True,True,True,True,...,False,False,True,True,True,True,True,True,True,True
2,True,True,True,False,True,False,True,False,True,False,...,False,False,False,False,False,True,False,True,False,False
3,True,True,True,False,True,True,True,True,True,True,...,False,False,True,True,False,True,False,True,True,False
4,True,True,True,False,True,True,True,False,True,True,...,False,False,False,False,False,True,False,True,True,False

In [507]:
mask.sum().sum()

1258536

In [508]:
mask.columns = ["Predicted" + str(p) for p in mask.columns]

In [509]:
sub[det_cls].head()

,Predicted2,Predicted3,Predicted4,Predicted6,Predicted7,Predicted8,Predicted9,Predicted10,Predicted12,Predicted13,...,Predicted559,Predicted562,Predicted563,Predicted564,Predicted565,Predicted566,Predicted567,Predicted568,Predicted570,Predicted571
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [510]:
delta = sub[det_cls].where(~mask)

In [511]:
delta.sum().sum()

45.0

In [439]:
delta.sum().sort_values()

Predicted252      0.0
Predicted296      0.0
Predicted302      0.0
Predicted306      0.0
Predicted307      0.0
                ...
Predicted310    217.0
Predicted10     279.0
Predicted96     285.0
Predicted372    533.0
Predicted374    563.0
Length: 204, dtype: float64

In [440]:
sub[det_cls] = sub[det_cls].where(mask, other=0.0)

In [441]:
d = sub[det_cls]

In [442]:
d[mask].sum().sum()

615.0

In [443]:
d[mask].sum().sort_values()

Predicted2        0.0
Predicted309      0.0
Predicted315      0.0
Predicted318      0.0
Predicted319      0.0
                ...
Predicted317     48.0
Predicted374     52.0
Predicted96      66.0
Predicted10      68.0
Predicted372    190.0
Length: 204, dtype: float64

In [444]:
df.head()

,id,height,seq_id,location,width,datetime,file_name,seq_frame_num,seq_num_frames,sub_location,...,559,562,563,564,565,566,567,568,570,571
0,8b31d3be-21bc-11ea-a13a-137349068a90,1024,a91ebc18-0cd3-11eb-bed1-0242ac1c0002,20,1280,2013-06-09 16:01:38.000,8b31d3be-21bc-11ea-a13a-137349068a90.jpg,0,10,NaN,...,1.515308e-28,7.845846e-31,1.171054e-15,6.766045e-16,1.222089e-19,5.284156e-16,9.663658e-26,2.293704e-16,1.757175e-16,4.467767e-17
1,8cf202be-21bc-11ea-a13a-137349068a90,1024,a91ebc18-0cd3-11eb-bed1-0242ac1c0002,20,1280,2013-06-09 16:01:39.000,8cf202be-21bc-11ea-a13a-137349068a90.jpg,1,10,NaN,...,1.515308e-28,7.845846e-31,1.171054e-15,6.766045e-16,1.222089e-19,5.284156e-16,9.663658e-26,2.293704e-16,1.757175e-16,4.467767e-17
2,8a87e62e-21bc-11ea-a13a-137349068a90,1024,a91ebc18-0cd3-11eb-bed1-0242ac1c0002,20,1280,2013-06-09 16:01:40.000,8a87e62e-21bc-11ea-a13a-137349068a90.jpg,2,10,NaN,...,1.515308e-28,7.845846e-31,1.171054e-15,6.766045e-16,1.222089e-19,5.284156e-16,9.663658e-26,2.293704e-16,1.757175e-16,4.467767e-17
3,8e6994f4-21bc-11ea-a13a-137349068a90,1024,a91ebc18-0cd3-11eb-bed1-0242ac1c0002,20,1280,2013-06-09 16:01:41.000,8e6994f4-21bc-11ea-a13a-137349068a90.jpg,3,10,NaN,...,1.515308e-28,7.845846e-31,1.171054e-15,6.766045e-16,1.222089e-19,5.284156e-16,9.663658e-26,2.293704e-16,1.757175e-16,4.467767e-17
4,948b29e2-21bc-11ea-a13a-137349068a90,1024,a91ebc18-0cd3-11eb-bed1-0242ac1c0002,20,1280,2013-06-09 16:01:42.000,948b29e2-21bc-11ea-a13a-137349068a90.jpg,4,10,NaN,...,1.515308e-28,7.845846e-31,1.171054e-15,6.766045e-16,1.222089e-19,5.284156e-16,9.663658e-26,2.293704e-16,1.757175e-16,4.467767e-17

In [445]:

sub.to_csv("metasub.csv", index=False)

In [446]:
hard_ones = [257, 130, 133, 402, 406, 407, 408, 412, 415, 417, 420, 296, 306, 571, 322, 323, 330, 77, 333, 80, 339, 342, 92, 349, 355, 356, 229, 114, 119, 250, 251, 252, 253]

In [447]:
hard_ids = ["Predicted" + str(h) for h in hard_ones]

In [448]:
sub[hard_ids].sum(axis=0).sum()

0.0